#!/bin/bash

_DEB_RELEASE="wheezy"					# stable | testing | unstable | jessie | wheezy | squeeze, ...
_APT_SOURCE="${_APT_SOURCE_RASPBIAN}"

_HOSTNAME="raspberry-pi"
_NET_CONFIG="dhcp"

_USER_NAME="root"
_USER_PASS="raspberry"

_KEYMAP="us"
_TIMEZONE="Europe/Berlin"
_LOCALES="en_US"
_ENCODING="UTF-8"
